language: julia
os:
  - windows
julia:
  - 1.1
  - 1.4
  - 1.5
branches:
  only:
    - master
coveralls: true
script:
  - julia --project=test/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
  - julia --project=test/ test/runtests.jl
  after_success: skip
notifications:
  email: false
