language: julia
os:
  - windows
julia:
  - 1.1
  - 1.4
  - 1.5
branches:
  only:
    - master
coveralls: true
script:
  - julia -e 'using Pkg'
  - julia --project=test test/runtests.jl
notifications:
  email: false
